name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      GCP_PROJECT_ID: ing-voice-team35
      GCP_PROJECT_NUMBER: "307966155885"
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Auth to Google Cloud via OIDC
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/${{ env.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "github-deployer@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker auth for Artifact Registry
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

    - name: Build & Push image (Cloud Build)
      run: |
        gcloud builds submit --tag "europe-west1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/ing-voice/ing-voice:latest" .

    - name: Deploy to Cloud Run
      run: |
        gcloud run services replace cloudrun.yaml --region=europe-west1
        gcloud run services add-iam-policy-binding ing-voice \
          --region=europe-west1 \
          --member="allUsers" \
          --role="roles/run.invoker"

    - name: Show Service URL
      run: gcloud run services describe ing-voice --region=europe-west1 --format='value(status.url)'
